services:
  # Transportadora A - EntregasRapidas
  entregas-rapidas:
    image: ghcr.io/goca-se/backend-challenge/entregas-rapidas:latest
    ports:
      - "6000:3000"
    restart: unless-stopped
    networks:
      - freight-network

  # Transportadora B - LogiFretes
  logi-fretes:
    image: ghcr.io/goca-se/backend-challenge/logi-fretes:latest
    ports:
      - "6001:3000"
    restart: unless-stopped
    networks:
      - freight-network

  # Transportadora C - MegaShipping
  mega-shipping:
    image: ghcr.io/goca-se/backend-challenge/mega-shipping:latest
    ports:
      - "6002:3000"
    restart: unless-stopped
    networks:
      - freight-network


networks:
  freight-network:
    driver: bridge 