version: '3'

services:
  entregas-rapidas-api:
    build: .
    container_name: entregas-rapidas-api
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 