name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Entregas Rapidas image
        uses: docker/build-push-action@v5
        with:
          context: ./entregas-rapidas
          push: true
          tags: ghcr.io/goca-se/backend-challenge/entregas-rapidas:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Logi Fretes image
        uses: docker/build-push-action@v5
        with:
          context: ./logi-fretes
          push: true
          tags: ghcr.io/goca-se/backend-challenge/logi-fretes:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Mega Shipping image
        uses: docker/build-push-action@v5
        with:
          context: ./mega-shipping
          push: true
          tags: ghcr.io/goca-se/backend-challenge/mega-shipping:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max 